### ISSUE TITLE
真机调试无法渲染报错

### ISSUE THREAD

**Issue by stephenml** [wechat-miniprogram/threejs-miniprogram#1]
手机预览正常，使用真机调试模式无法渲染，会报一个错误

```
remote-helper.js:1 eval script evaluate_id #11 failed TypeError: Cannot set property 'ontouchstart' of undefined
    at WAService.js:1:679251
    at Array.forEach (<anonymous>)
    at WAService.js:1:679222
    at WAService.js:1:679683
    at WAService.js:1:423621
    at Object.m (WAService.js:1:1905)
    at Object.value [as subscribeHandler] (C:\Users\ysh9818\AppData\Roaming\Tencent\微信开发者工具\package.nw\js\unpack\remote-helper.js:68:2165)
    at [VM 12]:1:17
    at Script.runInContext (vm.js:135:20)
    at Object.runInContext (vm.js:298:6)

```
![image](https://user-images.githubusercontent.com/11658803/64423267-ac13c180-d0d8-11e9-824c-dbfd0cc1626c.png)

**Comment by geshu** [comment]
这个问题是开发者工具不支持真机调试webgl，你直接预览就行。官方也在处理这个问题。
